### ISSUE TITLE
Add MQTT topics to handle Paradox PGM outputs

### ISSUE THREAD

**Issue by ducatidirk** [maisken/Paradox_IP150#17]
Programmable outputs on Paradox boards are often used to trigger gates, garage doors etc. Will be good to have control over these from Home Assistant.

**Comment by alfredopironti** [comment]
Hi,

Thanks for your interest in this project!

As far as I know, PGM outputs cannot be controlled via the IP150 web interface, so I'm afraid what you propose is something that cannot be achieved via this piece of software.

Closing issue for the time being. Please feel free to continue the discussion if you know of a way to control PGMs from the IP150 web interface.
