### ISSUE TITLE
Installation Instruction Issues

### ISSUE THREAD

**Issue by jwpwhite** [maisken/Paradox_IP150#18]
Awesome work @maisken!
I noticed two minor issue with the instructions:
1. configuration.yaml - Configuring PIR sensors (optional): "binary-sensor:" should be "binary_sensor:"
2. If you copy and paste the .yaml file settings, the quotation symbols cause me a lot of issues. When I replaced them with " from my PC keyboard, everything worked fine.

Hopefully this with save other a bit of time troubleshooting :)

**Comment by alfredopironti** [comment]
Nice catches! Thanks for reporting them, and glad someone's actually reading the docs ;-)

631314858ce29244988cc1da88d78836f5d9a73b should fix this. Please let me know if that works any better for you.
