### ISSUE TITLE
Issue when start Paradox IP150 MQTT Adapter

### ISSUE THREAD

**Issue by ygarand** [maisken/Paradox_IP150#19]
Hi All,

I have problem when I try to start the Paradox IP150 MQTT Adapter.  In the LOG I received this error.  Could you have some people to help me.

Thanks

`Traceback (most recent call last):
  File "ip150_mqtt.py", line 140, in <module>
    ip_mqtt.loop_forever()
  File "ip150_mqtt.py", line 122, in loop_forever
    self.ip.login(self._cfg['PANEL_CODE'], self._cfg['PANEL_PASSWORD'])
  File "/ip150.py", line 153, in login
    'Could not login, wrong credentials provided.')
ip150.Paradox_IP150_Error: Could not login, wrong credentials provided.`

**Comment by alfredopironti** [comment]
Hi,

According to the error message reported "Could not login, wrong credentials provided" you're using wrong credentials to access your paradox instance. Please make sure the right code and password used to access the web interface are set in the PANEL_CODE and PANEL_PASSWORD add-on configuration.

If you need further support, there's a lively community willing to help at https://community.home-assistant.io/t/paradox-alarm-mqtt-hassio-addon/38569

Hope this helps!
