### ISSUE TITLE
Add Backup Battery MQTT sensor

### ISSUE THREAD

**Issue by KameDomotics** [maisken/Paradox_IP150#26]
Hi!
Would it be possible to integrate the "battery backup" voltage sensor in the next updates?
Mqtt topic should be this:
`paradox/states/system/power/battery`

Thanks

**Comment by ondras12345** [comment]
Unless the battery voltage is available trough the IP module's web interface (and I don't think it is), this is impossible.
[PAI](https://github.com/ParadoxAlarmInterface/pai) is able to read the battery voltage because it uses a completely different method for retrieving data from the panel.

**Comment by KameDomotics** [comment]
> Unless the battery voltage is available trough the IP module's web interface (and I don't think it is), this is impossible.
> [PAI](https://github.com/ParadoxAlarmInterface/pai) is able to read the battery voltage because it uses a completely different method for retrieving data from the panel.

i believe this information is passing through IP150 web interface, but now i have no way to verify this...

**Comment by cybertza** [comment]
@KameDomotics PAI does not use the IPmodule HTTP for much, The do the serial calls for the data, I use PAI with a serial - wifi bridge that provides bare Serial, and i can see battery volts.
![image](https://user-images.githubusercontent.com/20600538/129631883-58e5a6bf-5f4d-480f-8fcd-07217147e9fb.png)

https://gitter.im/paradox-alarm-interface/community?at=5d9eeef549c7720aaf998b04

**Comment by alfredopironti** [comment]
Can you please provide a screenshot of the Paradox web interface displaying the backup battery voltage?

**Comment by alfredopironti** [comment]
Closing as stale.
